"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = RootLayout;
exports.metadata = void 0;
require("@/styles/main.scss");
// import "./globals.css";

// import Navbar from "../components/Organisms/Navbar";
var metadata = exports.metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};
function RootLayout(_ref) {
  var children = _ref.children;
  return /*#__PURE__*/React.createElement("html", {
    lang: "en"
  }, /*#__PURE__*/React.createElement("body", {
    className: ""
  }, /*#__PURE__*/React.createElement("main", {
    className: ""
  }, children)));
}