import type { Metadata } from "next";
// import "./globals.css";
import "@/styles/main.scss";
// import Navbar from "../components/Organisms/Navbar";
export const metadata: Metadata = {
  title: "WOLF🐺",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
