import type { Metadata } from "next";
// import "./globals.css";
import "@/styles/main.scss";
// import Navbar from "../components/Organisms/Navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        {/* <Navbar /> */}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
